const generateRandomString = () => {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const charactersLength = characters.length;
  for (let i = 0; i < 17; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
};

const firstNames = ['Liam', 'Kai', 'Leilani', 'Nalani', 'Kiana', 'Malakai', 'Keoni',
  'Lani', 'Kalea', 'Nani', 'Kaimana', 'Kekoa', 'Ikaika', 'Makana', 'Liko', 'Kapono',
  'Nohea', 'Aolani', 'Akoni', 'Kaipo', 'Mele', 'Kalani', 'Kaiwi', 'Halia', 'Akela',
  'Aloha', 'Emma', 'Noah', 'Olivia', 'William', 'Ava', 'James',
  'Isabella', 'Logan', 'Sophia', 'Benjamin', 'Mia', 'Mason', 'Charlotte', 'Elijah',
  'Amelia', 'Lucas', 'Hank', 'Oliver', 'Eve', 'Jackson', 'Abigail', 'Aiden', 'Emily',
  'Carter', 'Liz', 'Jayden', 'Mila', 'Ethan', 'Ella', 'Steve', 'Avery',
  'Alexander', 'Sofia', 'Michael', 'Camila', 'Matthew', 'Aria', 'Levi', 'Scarlett',
  'Nicholas', 'Victoria', 'Isaac', 'Chloe', 'Daniel', 'Madison', 'Joseph', 'Grace',
  'Samuel', 'Lily', 'Eleanor', 'Chidi', 'Tahani', 'Jason', 'Michael', 'Janet', 'Derek',
  'Vicky', 'Glenn', 'Simone', 'Brent', 'John', 'Kamilah', 'Mindy', 'Doug', 'Joy', 'Evelyn',
  'Avery', 'Blake', 'Caleb', 'Dylan', 'Ellie', 'Gavin', 'Haley', 'Isaac', 'Jaden', 'Kayla', 'Liam',
  'Mason', 'Nolan', 'Oliver', 'Piper', 'Quinn', 'Riley', 'Sadie', 'Tyler', 'Violet', 'Wyatt', 'Xander',
  'Yara', 'Zoe', 'Waymond', 'Deirdre',
];

export const Reviews = [
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'This recipe was fantastic! My whole family loved it.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 2),
    comment: 'This recipe was pretty good, but I think it could use some more flavor.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 1),
    comment: "This recipe didn't turn out great. I'm not sure what went wrong.",
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'I really enjoyed this recipe. It was easy to make and tasted great.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 1,
    comment: 'I did not like this recipe at all. It was very bland.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'This recipe was amazing! I loved the combination of flavors.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'The recipe was easy to follow and turned out great!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 2),
    comment: 'I thought this recipe was just okay. It was a bit too spicy for my taste.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 1,
    comment: 'This recipe was a disaster! I followed the instructions exactly and it still turned out terrible.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'I really enjoyed making this recipe. It was a lot of fun!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'This recipe was delicious! I will definitely be making it again.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 2),
    comment: 'I had high hopes for this recipe, but it didn\'t turn out as expected.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'This recipe was a big hit with my friends! I will be making it again.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 3),
    comment: 'The recipe was a bit too complicated for me, but the end result was worth it.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() + 4),
    comment: 'I loved making this recipe! It was easy and delicious.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'This recipe was absolutely amazing! I can\'t wait to make it again.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'My family and I loved this recipe. It was so delicious!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe was pretty good, but it could use a little more seasoning. Overall, I think I would make it again',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'I\'m in love with this recipe! It\'s definitely one of my new favorites.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe was good, but it didn\'t blow me away. Still worth making though!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'The recipe was a bit bland and could use more flavor, but I appreciate the effort put into creating it.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'The recipe was average, but I think it could be improved with some more seasoning or herbs.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() * 3),
    comment: 'This recipe was okay, but it could have been better. There were some aspects of it that I didn\'t really enjoy.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: Math.round(Math.random() * 3),
    comment: 'It wasn\'t my favorite recipe, but it wasn\'t terrible either. I\'m not sure if I would make it again, but it was worth a try.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'This recipe is out of this world! The flavors are perfectly balanced and it\'s so easy to make. I\'m in love!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'Absolutely delicious! I can\'t believe I made this myself. It\'s now a family favorite!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'This recipe exceeded my expectations! I can\'t stop raving about it. It\'s so tasty and comforting.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'Wow, this is the best thing I\'ve ever tasted! I followed the recipe exactly and it turned out perfectly. I can\'t wait to make it again!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 5,
    comment: 'I\'m blown away by how amazing this recipe is! It\'s simple, flavorful, and perfect for any occasion. Highly recommend!',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe is good, but it\'s missing a little something. I added some extra seasoning and it really made a difference. Would make again with some tweaks.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe is pretty good. It\'s easy to make and has good flavor. It\'s not my favorite, but it\'s definitely worth trying.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe is tasty, but a little on the bland side. I would recommend adding some more spice or seasoning to give it a kick.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe is decent, but it\'s not amazing. It\'s good for a quick weeknight meal, but I wouldn\'t serve it to guests.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 4,
    comment: 'This recipe is fine, but it didn\'t blow me away. I think it could use some more depth of flavor. It\'s a good starting point, though.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'This recipe is okay, but it\'s not anything special. I wouldn\'t go out of my way to make it again, but I wouldn\'t turn it down if someone served it to me.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'This recipe has potential, but it needs some work. I found it a bit too salty and the texture was a bit off. Might try it again with some adjustments.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'This recipe was decent, but it wasn\'t my favorite. It had good flavor, but I found it a bit too rich for my taste.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'This recipe was alright, but it didn\'t wow me. I think it could use some more spices or herbs to really bring out the flavors.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 3,
    comment: 'This recipe was fine, but it didn\'t stand out. It was easy to make, but I think it needs something to make it more interesting.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'This recipe was not great. The flavors didn\'t work well together and it ended up being very bland. Would not make again.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'This recipe was a disappointment. It looked good, but the taste was very underwhelming. I followed the instructions exactly and it still didn\'t turn out well.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'This recipe was just okay. It didn\'t have enough flavor and the texture was a bit off. I wouldn\'t make it again, but I didn\'t hate it either.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'This recipe was not my favorite. It had a weird aftertaste and the texture was a off-putting. I think there are better recipes out there for this dish',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
  {
    userID: generateRandomString(),
    user: `${firstNames[Math.floor(Math.random() * firstNames.length)]}${Math.floor(Math.random() * 900) + 100}`,
    rating: 2,
    comment: 'This recipe was a miss for me. It was too much and the flavors didn\'t come together well. I think it needs some serious tweaking before it can be a good recipe.',
    created: new Date(Date.now() - Math.floor(Math.random() * (7 * 24 * 60 * 60 * 1000))),
  },
];
